//
//  CartPositionsPresenter.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 28/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartPositionsPresentationLogic
{
  func presentSomething(response: CartPositions.Something.Response)
}

class CartPositionsPresenter: CartPositionsPresentationLogic
{
  weak var viewController: CartPositionsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CartPositions.Something.Response)
  {
    let viewModel = CartPositions.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
