//
//  CartPositionsViewController.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 28/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartPositionsDisplayLogic: class
{
  func displaySomething(viewModel: CartPositions.Something.ViewModel)
}

class CartPositionsViewController: UIViewController, CartPositionsDisplayLogic
{
  var interactor: CartPositionsBusinessLogic?
    
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    showPositions()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func showPositions()
  {
    let request = CartPositions.Positions.Request()
    interactor?.showPositions(request: request)
  }
  
  func displayPositions(viewModel: CartPositions.Positions.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
