//
//  CartPositionsInteractor.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 28/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CartPositionsBusinessLogic
{
  func showPositions(request: CartPositions.Positions.Request)
}

protocol CartPositionsDataStore
{
  var cart: Cart { get set }
}

class CartPositionsInteractor: CartPositionsBusinessLogic, CartPositionsDataStore
{
    var presenter: CartPositionsPresentationLogic?
    var worker: CartPositionsWorker?
    var cart: Cart = CartManager.sharedInstance.currentCart()
  
    // MARK: Show positions
    
    func showPositions(request: CartPositions.Positions.Request)
    {
        worker = CartPositionsWorker()
        worker?.doSomeWork()
        
        let response = CartPositions.Positions.Response()
        presenter?.presentSomething(response: response)
    }
}
