//
//  CartPresenterTests.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TyphoonExample
import XCTest

class CartPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CartPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCartPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCartPresenter()
  {
    sut = CartPresenter()
  }
  
  // MARK: Test doubles
  
  class CartDisplayLogicSpy: CartDisplayLogic
  {
    func displayCart(viewModel: CartModels.CurrentCart.ViewModel) {
        displayCartCalled = true
    }
    
    var displayCartCalled = false
    
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = CartDisplayLogicSpy()
    sut.viewController = spy
    let cart = Cart(id: "1", created: Date())
    let response = CartModels.CurrentCart.Response(cart: cart)
    
    // When
    sut.presentCurrentCart(response: response)
    
    // Then
    XCTAssertTrue(spy.displayCartCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
