//
//  CartInteractor.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartBusinessLogic
{
  func loadCurrenCart(request: CartModels.CurrentCart.Request)
}

protocol CartDataStore
{
    var cart: Cart? { get }
}

class CartInteractor: CartBusinessLogic, CartDataStore
{
    var presenter: CartPresentationLogic?
    var worker: CartWorker?
    var cart: Cart?

  // MARK: Do something
  
  func loadCurrenCart(request: CartModels.CurrentCart.Request)
  {
    worker = CartWorker()
    cart = worker?.loadCurrenCart()
    
    let response = CartModels.CurrentCart.Response(cart: cart!)
    presenter?.presentCurrentCart(response: response)
  }
}
