//
//  CartWorker.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CartWorker
{
    var cartManager : CartManagerProtocol
    
    init() {
        cartManager = CartManagerSingleton()
    }
    
    func loadCurrenCart() -> Cart
    {
        return cartManager.currentCart()
    }
}
