//
//  CartViewController.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartDisplayLogic: class
{
    func displayCart(viewModel: CartModels.CurrentCart.ViewModel)
}

class CartViewController: UIViewController, CartDisplayLogic
{
    var interactor: CartBusinessLogic?
    var router: (NSObjectProtocol & CartRoutingLogic & CartDataPassing)?
    
    @IBOutlet weak var cartIdLbl: UILabel!
    @IBOutlet weak var cartDateLbl: UILabel!
    
    var displayedCart: CartModels.CurrentCart.ViewModel.DisplayedCart?
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        loadCurrenCart()
    }
    
    // MARK: loadCurrenCart
    
    func loadCurrenCart()
    {
        let request = CartModels.CurrentCart.Request()
        interactor?.loadCurrenCart(request: request)
    }
    
    func displayCart(viewModel: CartModels.CurrentCart.ViewModel)
    {
        displayedCart = viewModel.displayedCart
        cartIdLbl.text = displayedCart?.id
        cartDateLbl.text = displayedCart?.created
    }
}
