//
//  CartRouter.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 28/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CartRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CartDataPassing
{
  var dataStore: CartDataStore? { get }
}

class CartRouter: NSObject, CartRoutingLogic, CartDataPassing
{
  weak var viewController: CartViewController?
  var dataStore: CartDataStore?
  
    static func assembleCart(id : String) -> UIViewController {
        
        let viewController = UIStoryboard(name: "Cart", bundle: nil).instantiateViewController(withIdentifier: "Cart") as! CartViewController
        
        let presenter = CartPresenter()
        let interactor = CartInteractor()
        let router = CartRouter()
        
        // VIP
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        
        return viewController
    }
    
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CartViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CartDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
