//
//  CartRouter.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CartRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CartDataPassing
{
    var dataStore: CartDataStore? { get }
}

class CartRouter: NSObject, CartRoutingLogic, CartDataPassing
{
    weak var viewController: CartViewController?
    var dataStore: CartDataStore?
    
    static func assembleCart() -> UIViewController {
        let viewController = UIStoryboard(name: "Cart", bundle: nil).instantiateViewController(withIdentifier: "CartViewController") as! CartViewController
        
        let presenter = CartPresenter()
        let interactor = CartInteractor()
        let router = CartRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        
        return viewController
    }
    
}
