//
//  CartModels.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum CartModels
{
    // MARK: Use cases
    
    enum CurrentCart
    {
        struct Request
        {
        }
        struct Response
        {
            var cart : Cart
        }
        struct ViewModel
        {
            struct DisplayedCart
            {
                var id : String
                var created : String
            }
            var displayedCart: DisplayedCart
        }
    }
}
