//
//  CartPresenter.swift
//  TyphoonExample
//
//  Created by Valerio Ferrucci on 30/07/18.
//  Copyright (c) 2018 Valerio Ferrucci. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartPresentationLogic
{
    func presentCurrentCart(response: CartModels.CurrentCart.Response)
}

class CartPresenter: CartPresentationLogic
{
    weak var viewController: CartDisplayLogic?
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none
        return dateFormatter
    }()
    
    func presentCurrentCart(response: CartModels.CurrentCart.Response)
    {
        let cart = response.cart
        let createdStr = dateFormatter.string(from: cart.created)
        let displayedCart = CartModels.CurrentCart.ViewModel.DisplayedCart(id: cart.id, created: createdStr)
        let viewModel = CartModels.CurrentCart.ViewModel(displayedCart: displayedCart)
        viewController?.displayCart(viewModel: viewModel)
    }
}
